### ISSUE TITLE
Add loadouts to operators

### ISSUE THREAD

**Issue by danielwerg** [danielwerg/r6data#1]
### Feature

Each operator should have their own loadout.
https://github.com/marcopixel/r6operators/issues/6

### Ideal solution or implementation

<details><summary>Show</summary>

`src/operators/recruit_attack/index.ts`:

```diff
// ...

export const recruitAttack = {
  slug: 'recruit_attack',
  // ...
-  weapons: {
-    primary: ['l85a2', 'mk_14_ebr', 'm249'],
-    secondary: ['p12', 'super_shorty', 'c75_auto']
-  },
+  weapons: {
+    primary: [
+      {
+        slug: 'l85a2',
+        sights: ['holo_a'],
+        barrels: ['flash_hider'],
+        grips: ['vertical_grip'],
+        underBarrels: null
+      },
+      {
+        slug: 'mk_14_ebr',
+        sights: ['scope_3.0x'],
+        barrels: ['muzzle_brake'],
+        grips: ['vertical_grip'],
+        underBarrels: null
+      },
+      {
+        slug: 'm249',
+        sights: ['reflex_a'],
+        barrels: ['compensator'],
+        grips: ['vertical_grip'],
+        underBarrels: null
+      }
+    ],
+    secondary: [
+      {
+        slug: 'p12',
+        sights: null,
+        barrels: ['suppressor'],
+        grips: null,
+        underBarrels: null
+      },
+      {
+        slug: 'super_shorty',
+        sights: null,
+        barrels: null,
+        grips: null,
+        underBarrels: ['laser']
+      },
+      {
+        slug: 'c75_auto',
+        sights: null,
+        barrels: null,
+        grips: null,
+        underBarrels: null
+      }
+    ]
+  },
  // ...
} satisfies Operator;
```

`src/operators/types.ts`:

```ts
export interface OperatorWeapons {
  primary: OperatorWeapon[];
  secondary: OperatorWeapon[];
}

export interface OperatorWeapon {
  slug: WeaponSlug;
  sights: SightSlug[] | null;
  barrels: BarrelSlug[] | null;
  grips: GripSlug[] | null;
  underBarrels: UnderBarrelSlug[] | null;
}
```

</details>

#### Handle forced attachments

<details><summary>Examples:</summary>

https://github.com/danielwerg/r6data/blob/feat/operator-weapon-loadouts/src/operators/caveira/index.ts#L46
https://github.com/danielwerg/r6data/blob/feat/operator-weapon-loadouts/src/operators/echo/index.ts#L42
https://github.com/danielwerg/r6data/blob/feat/operator-weapon-loadouts/src/operators/ela/index.ts#L49

</details>

**Comment by danielwerg** [comment]
@PandaDriver156 I have published a branch - https://github.com/danielwerg/r6data/tree/feat/operator-weapon-loadouts. Will start working on *defenders*, fork that branch instead of master.

**Comment by PandaDriver156** [comment]
> @PandaDriver156 I have published a branch - https://github.com/danielwerg/r6data/tree/feat/operator-weapon-loadouts. Will start working on _defenders_, fork that branch instead of master.

Thanks, I'll start working on attackers tomorrow then.

**Comment by danielwerg** [comment]
Not sure what is a best way to handle "forced" attachments. Here is few example to show what I mean:

https://github.com/danielwerg/r6data/blob/feat/operator-weapon-loadouts/src/operators/caveira/index.ts#L46
https://github.com/danielwerg/r6data/blob/feat/operator-weapon-loadouts/src/operators/echo/index.ts#L42
https://github.com/danielwerg/r6data/blob/feat/operator-weapon-loadouts/src/operators/ela/index.ts#L49

Just going to leave comments for now.

**Comment by danielwerg** [comment]
Awesome, I thinks there so much we can do for `sights` but we should have a var for `barrels` without extended barrel.
Target https://github.com/danielwerg/r6data/tree/feat/operator-weapon-loadouts branch

**Comment by danielwerg** [comment]
I'm not good at naming things, but maybe something like this?
```diff
- export const COMMON_BARRELS = [
-   'flash_hider',
-   'compensator',
-   'muzzle_brake',
-   'suppressor',
-   'extended_barrel'
- ] satisfies BarrelSlug[];

+ export const COMMON_BARRELS_NO_EXTENDED_BARREL = [
+   'flash_hider',
+   'compensator',
+   'muzzle_brake',
+   'suppressor'
+ ] satisfies BarrelSlug[];

+ export const COMMON_BARRELS_ALL = [
+   'flash_hider',
+   'compensator',
+   'muzzle_brake',
+   'suppressor',
+   'extended_barrel'
+ ] satisfies BarrelSlug[];
```
