### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by BadCoder1337** [danielwerg/r6data#4]
### Feature

Since `r6data` package doesn't bring network features, it's completely possible to make it browser compatible. Currently it uses `fs` to load `.md` notes and `.svg` graphics. 

### Ideal solution or implementation

Webpack provides the way to load non-code assets.
Notes could be [inlined](https://webpack.js.org/guides/asset-modules/#source-assets). `.svg` content could be provided [as URL](https://webpack.js.org/guides/asset-modules/#url-assets) with different [base path](https://webpack.js.org/guides/public-path) for different environments. At the browser side we could tweak asset base path (e.g. GitHub repo or CDN), at the server side we could load asset content with [`file://` protocol](https://stackoverflow.com/a/55665315)  

### Alternative solutions or implementations

Export `.md` content as string in `.js` file . Provide `.svg` graphic as asset URL like `.png`.

### Other context

I would like to contribute some things and use the lib as data transformer for web/Node. E.g. processing raw seasonal data from different sources (before Operation Health - `prod.datadev.ubisoft.com`, Health to Brutal Swarm - `r6karma/players`, Solar Raid and further - Ranked 2.0 at `r6s/skill/full_profiles` or Ranked 1.0 at `r6karma/players` from crossplay `spaceId`) and transforming into understandable (rating, rank, W/R, K/D, etc.). It would require some additional Ubi constants and advanced schema validator.
![image](https://user-images.githubusercontent.com/16510197/224398414-ce779392-008e-4b3c-94f4-52e334df5e78.png)

**Comment by danielwerg** [comment]
Not sure what "Other context" sections implies. As for browser compatibility you are welcome to open pr. Definitely will have to add a bundle, but I don't want to use webpack, got traumatized last time I used it for big project ~2 years ago and it was so damn slow with all the plugins I had to use.

**Comment by danielwerg** [comment]
@BadCoder1337 and anyone who might be reading this, I just published [browser](https://github.com/danielwerg/r6data/tree/browser ) branch which provides browser support using vite. Can you please test it in your environment?
